# Generated by Django 6.0.5 on 2026-05-11 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('curso', models.CharField(max_length=50)),
                ('periodo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('git', models.URLField(blank=True)),
                ('linked', models.URLField(blank=True)),
                ('url_imagem', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Pessoal',
                'verbose_name_plural': 'Perfis Pessoais',
            },
        ),
    ]
