# Generated by Django 6.0.5 on 2026-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('url_icone', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('Pessoal', 'Projeto Pessoal'), ('Acadêmico', 'Projeto Acadêmico'), ('Profissional', 'Projeto Profissional')], default='Pessoal', max_length=20)),
                ('link_git', models.URLField()),
                ('tecnologias', models.ManyToManyField(to='portifolio.tecnologia')),
            ],
        ),
    ]
